allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

minimumReleaseAgeExclude:
  - '@floating-ui/core@1.8.0'
  - '@floating-ui/dom@1.8.0'
  - '@floating-ui/utils@0.2.12'
  - '@iconify-json/lucide@1.2.118'
  - '@iconify-json/simple-icons@1.2.90'
  - '@nuxt/ui@4.10.0'
  - '@tanstack/virtual-core@3.17.4'
  - '@tanstack/vue-virtual@3.13.32'
  - '@vue/language-core@3.3.7'
  - eslint@10.7.0
  - fuse.js@7.5.0
  - vue-component-type-helpers@3.3.7
  - vue-tsc@3.3.7

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
